# Generated by Django 6.0 on 2025-12-27 10:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_deadline', models.DateTimeField()),
                ('rsvp_deadline_passed_text', models.TextField()),
                ('restrictions_text', models.TextField()),
                ('confirm_yes_text', models.TextField()),
                ('confirm_partial_text', models.TextField()),
                ('confirm_no_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('max_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_e164', models.CharField(blank=True, default='', max_length=20)),
                ('show_restrictions_text', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, choices=[('YES', 'Sí asisto'), ('NO', 'No asisto')], max_length=3, null=True)),
                ('tickets_confirmed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='invitations.party')),
            ],
        ),
    ]
