# Generated by Django 6.0 on 2025-12-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfig',
            old_name='confirm_no_text',
            new_name='confirm_text_no',
        ),
        migrations.RenameField(
            model_name='appconfig',
            old_name='confirm_partial_text',
            new_name='confirm_text_partial',
        ),
        migrations.RenameField(
            model_name='appconfig',
            old_name='confirm_yes_text',
            new_name='confirm_text_yes',
        ),
        migrations.RenameField(
            model_name='appconfig',
            old_name='rsvp_deadline_passed_text',
            new_name='rsvp_deadline_passed_text_no',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='rsvp_deadline_passed_text_partial',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appconfig',
            name='rsvp_deadline_passed_text_yes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
