# Generated by Django 6.0 on 2025-12-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_rename_confirm_no_text_appconfig_confirm_text_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='rsvp_deadline_passed_text_none',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
