# Generated by Django 6.0 on 2025-12-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_appconfig_rsvp_deadline_passed_text_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='invite_message_template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
