# Generated by Django 6.0 on 2025-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_appconfig_invite_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='invite_password',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
